### ISSUE TITLE
Not downloading latest update through composer

### ISSUE THREAD

**Issue by cluwong** [devleaks/yii2-metafizzy#3]
When tried to install via composer, the source path does not reflect the lastest change - it's still showing '@vendor/.....' and not '@bower/....'
Have tried both "devleaks/yii2-metafizzy": "*" and "devleaks/yii2-metafizzy": "dev-master" in composer.json.

**Comment by devleaks** [comment]
Bumped release to 1.0.2. Should be ok. Sorry bout that. P.
